version: "3.8"

services:
  postgres:
    container_name: technoparkweb-postgres
    image: postgres
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: technoparkweb
    ports:
      - "8000:5432"
    restart: unless-stopped

  keycloak:
#    image: jboss/keycloak
    image: sleighzy/keycloak
    container_name: technoparkweb-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: technoparkweb
      DB_USER: k_app
      DB_PASSWORD: 123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"

  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technoparkweb-app
    ports:
        - "8080:8000"
    depends_on:
        - postgres
        - keycloak